## Secret is also much like config map but in secrets the values are base64 encoded
## Secretes has 3 available commands
## tls: secret for holding private-public key for communicating with TLS protocol
## docker-registry: This is special kind of secret that stores usernames and passwords 
## to connect to private registries.




### kubectl create secret generic db-secret --from-literal=db_user=pravin --from-literal=db_password=test1234
### declare varible as environment variable
## kubectl exec -it secret-busybox -- printenv | grep DB


apiVersion: v1
kind: Pod
metadata:
  name: secret-busybox
spec:
  containers:
  - name: secret-busybox
    image: busybox
    command:
     - sleep
     - "3600"
    env:
      - name: DB_USER  ## Provide the variable name to map the value
        valueFrom:
          secretKeyRef:
            name: db-secret  ## Name of the secret created
            key: db_user  ## The key to fetch
      - name: DB_PWD  ## Provide the variable name to map the value
        valueFrom:
          secretKeyRef:
            name: db-secret  ## Name of the secret created
            key: db_password  ## The key to fetch
