apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-vm
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: retain
  storageClassName: manual
  hostPath:
    paht: /mnt/data
  

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual


# k create -f pv.yml
# k create -f pvc.yml
