

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: pravin
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ216Q0NBWU1DQVFBd1ZqRUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeApJVEFmQmdOVkJBb01HRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERVBNQTBHQTFVRUF3d0djSEpoCmRtbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhXVEtNT3NkcWdzcHEzZ1QKT0FwNEcrMHJ0QjkvVE15TnlyYUo3aERvMHdhVlZCOU9qZkduK0NZOFYwK1lvQnRnN0pjb1YzcGdyRGh4SFIwbgpJd0NlWFNzWGVEVkZsTlZkZzlGNTZoZlg1cm1iV3lTVXZCR1R6NFNHcm9QZ3hyY0JkTFg0V0hLMUJkN3Y3NjdSCkttMjBjV3RTaXlSdHl0YVJGRGVYRHdTMUt6WEFMd2FBeHBrdnNuTlA1czM5Z2FIMnYrR3QvZ25TWm9QUmF1QmsKOU82MGdDU3FSbmF2UUVLbmJWaXR1b1FrRkhPTUNqdnkraWJRekdoTWlEQWFHb1BZdnZaam16MFdjUktobk8xeAp4a3FSY2xDd0MxUWpOaFJZNEo1VDl3aDhRWFgxQkUxTDc2cDVMN1B4ZkU3QlRqeG9Gd0NxelB6eE55Z2IwWkNCCld6Tzdad0lEQVFBQm9BQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXVLd3liOVRnZURSVkxXRnJNcVRKanMKZ1kvOWx5UnMzTlNmMWhXN1NBeXdqMWF2UFduQXVqYlBSVHBjVzhvK2FCT1I3bzZvK2RtUDZFRkZBZ2NMd213bgpod0lXblE5dFIybVluTkpHbnNIR2pIRFdDMTRPWTM2YVovNXQzQnpLV3dmMFZhMmFjVnptTnovVGM0aHZWcm5SCmV4MXhIWW5IcStPVFZwMytocmNXN1Q2MWN3ZWRwYlc2cDhwNDJTczQwYjBNV0tIdkRRVnNXUllKalVkaUhRRDYKWlA4TzRsMWVoZ1RTQnFRTEFuUllXR3lvNkt3WUlWMHNqb2UyNXZkS2IrVVRqcmxndlIxVStTcXYxb0hvQmVHMwp6TlQ5T0pXeEdDdXkvQkFRRVpabXdjZWdZemhwdWROSVgzMkV0ZXFxeDNMQ1AvL0xSVUxqQjA5ZkEwQjN2TFk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth 

  