---
apiVersion: v1
kind: namespace
metadata:
  name: devops-ns
spec: {}
status: {}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops
  namespace: devops-ns
rules:
- apigroups: ["", "extentions", "aaps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
apiVersion:  rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops
  namespace: devops-ns
subjects:
- kind: user
  name: devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops

  #------------------- CertificationSigningRequest
# apiVersion: Certificates.k8s.io/v1beta1
# kind: CertificationSigningRequest
# metadata:
#   name: user-req
# spec:
#   groups:
#   - system: authenticated
#   request: Ls0g$rsfsc
#   usages:
#   - digital signature
#   - key inciphermate
#   - client auth
