---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: pod-reader
  namespace: rbacns
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pravin
  namespace: rbacns

